remote_theme: son-link/jekyll-theme-space
plugins:
- jekyll-paginate
paginate: 5 # Posts per page
paginate_path: "page:num/"
# Site settings
title: OlavWoliken
description: 17yo · any neutral · INFP-T · writer
