theme: jekyll-simple-dark
plugins:
- jekyll-paginate
- jekyll-seo-tag #if you use this.
paginate: 5 # Posts per page
paginate_path: "page:num/"
# Site settings
title: OlavWoliken
description: 17yo · any neutral · INFP-T · writer
